Add conversations table field for picture location
schramm-famm/ether pull request #22
Opened 2020-02-28 17:53 UTC by HonorL

Updated conversation handlers to include avatar url.
Added and updated tests for new field.

2020-02-28 20:50 UTC, Thao-Tran requested changes
Looks good!

2020-02-28 20:50 UTC, Thao-Tran commented on DBSchema.sql
> +	AvatarURL VARCHAR(255),
Change it from a tab to 4 spaces, so that it lines up with the other ones.
```suggestion
    AvatarURL VARCHAR(255),
```

2020-02-28 22:34 UTC, igorveselinovic approved these changes
Looks good. Just fix the thing TT mentioned.

2020-03-01 01:13 UTC, Thao-Tran approved these changes

2020-03-01 01:48 UTC, merged